const basePath = "/images/excos/";

export const excoData = [
    {
        name: "Matthew Ryan Teo",
        role: "President",
        year: "'24",
        major: "Computer Science and Engineering",
        photo: basePath + "president.jpg",
        altPhoto: "",
        alt: "Photo of Matt",
    },
    {
        name: "Tania Tan",
        role: "Internal Vice President",
        year: "'25",
        major: "Psychology",
        photo: basePath + "ivp.jpg",
        altPhoto: "",
        alt: "Photo of Tania",
    },
    {
        name: "Pierce Chong",
        role: "External Vice President",
        year: "'24",
        major: "Computer Science",
        photo: basePath + "evp.jpg",
        altPhoto: "",
        alt: "Photo of Pierce",
    },
    {
        name: "Bowen Zheng",
        role: "Finance Director",
        year: "'25",
        major: "Applied Math",
        photo: basePath + "finance.jpg",
        altPhoto: "",
        alt: "Photo of Bowen",
    },
    {
        name: "Yanisa Kee",
        role: "Events Director",
        year: "'26",
        major: "Business Economics and Sociology",
        photo: basePath + "events.jpg",
        altPhoto: "",
        alt: "Photo of Yanisa",
    },
    {
        name: "Jessica Ti",
        role: "Publicity Director",
        year: "'26",
        major: "Cognitive Science",
        photo: basePath + "publicity.jpg",
        altPhoto: "",
        alt: "Photo of Jessica",
    },
    {
        name: "Kai Jun Tay",
        role: "Partnerships Director",
        year: "'24",
        major: "Computer Engineering",
        photo: basePath + "partnerships.jpg",
        altPhoto: "",
        alt: "Photo of Kai",
    },
    {
        name: "Hazim Bin Fathul Rahman",
        role: "Advisor",
        year: "'24",
        major: "Legal Studies",
        photo: basePath + "advisor.jpg",
        altPhoto: basePath + "elmo.png",
        alt: "Photo of Hazim",
    },
    {
        name: "Ariane Cazaubon",
        role: "Committee Member",
        year: "'26",
        major: "Neuroscience and English",
        photo: basePath + "committeeMember1.jpg",
        altPhoto: basePath + "rat.jpg",
        alt: "Photo of Ariane",
    },
    {
        name: "Jonathan Ng",
        role: "Committee Member",
        year: "'26",
        major: "MCDB",
        photo: basePath + "committeeMember2.jpg",
        altPhoto: "",
        alt: "Photo of Jonathan",
    },
    {
        name: "Ella Liu",
        role: "Committee Member",
        year: "'26",
        major: "Psychology",
        photo: basePath + "committeeMember3.jpg",
        altPhoto: basePath + "deer.png",
        alt: "Photo of Ella",
    },
]