const basePath = "/images/excos/";

export const excoData = [
    {
        name: "Aaron Tan",
        role: "President",
        year: "'26",
        major: "Mechanical Engineering",
        photo: basePath + "president.jpg",
        altPhoto: "",
        alt: "Photo of Aaron",
    },
    {
        name: "Ariane Cazaubon",
        role: "Internal Vice President",
        year: "'26",
        major: "Neuroscience and English",
        photo: basePath + "ivp.jpg",
        altPhoto: basePath + "ivp_alt.jpg",
        alt: "Photo of Ariane",
    },
    {
        name: "Jessica Ti",
        role: "External Vice President",
        year: "'25",
        major: "Cognitive Science and Film",
        photo: basePath + "evp.jpg",
        altPhoto: "",
        alt: "Photo of Jessica",
    },
    {
        name: "Chong Min-shin",
        role: "Finance Director",
        year: "'27",
        major: "Business Economics",
        photo: basePath + "finance.jpg",
        altPhoto: "",
        alt: "Photo of Min-shin",
    },
    {
        name: "Russell Luo",
        role: "Events Director",
        year: "'27",
        major: "Data Theory",
        photo: basePath + "events.jpg",
        altPhoto: "",
        alt: "Photo of Russell",
    },
    {
        name: "Kyra Koh",
        role: "Publicity Director",
        year: "'27",
        major: "Electrical Engineering",
        photo: basePath + "publicity.jpg",
        altPhoto: basePath + "publicity_alt.jpg",
        alt: "Photo of Kyra",
    },
    {
        name: "Priscilla Lim",
        role: "Partnerships Director",
        year: "'25",
        major: "Chemical Engineering",
        photo: basePath + "partnerships.jpg",
        altPhoto: "",
        alt: "Photo of Pris",
    },
    {
        name: "Alex Su",
        role: "Technology Director",
        year: "'26",
        major: "Computer Science and Engineering",
        photo: basePath + "technology.jpg",
        altPhoto: basePath + "technology_alt.jpg",
        alt: "Photo of Alex",
    },
    {
        name: "Pierce Chong",
        role: "Advisor",
        year: "'25",
        major: "MSc Computer Science",
        photo: basePath + "advisor2.jpg",
        altPhoto: "",
        alt: "Photo of Pierce",
    },
    {
        name: "Bowen Zheng",
        role: "Advisor",
        year: "'25",
        major: "Applied Mathematics",
        photo: basePath + "advisor1.jpg",
        altPhoto: "",
        alt: "Photo of Bowen",
    },
]